version: "3.1"
services:
  api:
    image: "bancard_payments_api_template_api:latest"
    restart: always
    tty: true
    stdin_open: true
    env_file: .env
    depends_on:
      - db
    command: python3 api.py
  nginx:
    image: "bancard_payments_api_template_nginx:latest"
    env_file: .env
    ports:
      - "$COMPOSE_NGINX_EXTERNAL_PORT:80"
    depends_on:
      - backend
      - admin
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - logs:/logs
  db:
    image: "postgres:14"
    ports:
      - "$COMPOSE_DATABASE_EXTERNAL_PORT:5432"
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: $COMPOSE_DATABASE_USER
      POSTGRES_PASSWORD: $COMPOSE_DATABASE_PASSWORD
      POSTGRES_DB: $COMPOSE_DATABASE_NAME
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  logs: {}
  database: {}
